"""initial_migrations

Revision ID: 964460427eb9
Revises:
Create Date: 2025-10-14 21:10:37.530317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "964460427eb9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "category",
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="fk_category_created_by_user_id"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name="fk_category_updated_by_user_id"),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("category_uid", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image", sa.String(length=64), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["category_uid"], ["category.uid"], name="fk_product_category_uid"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="fk_product_created_by_user_id"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name="fk_product_updated_by_user_id"),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name", "category_uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    op.drop_table("category")
    op.drop_table("user")
    # ### end Alembic commands ###
